version: '3.7'
services:
  base: &base
    image: alpine:edge
    volumes:
    - .:/infra
    - /var/run/docker.sock:/var/run/docker.sock:ro
    # - ./aws-iam-authenticator:/usr/local/bin/aws-iam-authenticator
    #- /usr/local/bin/aws-iam-authenticator:/usr/local/bin/aws-iam-authenticator
    working_dir: /infra
    restart: 'no'
    tty: true
    env_file:
    - .env

  helmfile:
    <<: *base
    image: abdennour/helmfile:v0.85.3 # quay.io/roboll/helmfile:v0.85.3
    entrypoint: helmfile

  kubectl:
    <<: *base
    image: abdennour/kubectl:v1.14.7-aws1.16.246
    # entrypoint: kubectl


  helm2:
    <<: *base
    image: abdennour/helmfile:v0.85.3 # quay.io/roboll/helmfile:v0.85.3
    entrypoint: helm
  
  helm:
    image: abdennour/helm:3.1.2-aws1.18.21-kubectlv1.17.4
    restart: "no"
    working_dir: /code
    volumes:
    - .:/code
    # - ${HOME}/.kube:/root/.kube:ro
    - helm-config:/root/.config/helm
    - helm-cache:/root/.cache/helm
    environment:
      KUBECONFIG: /root/kubeconfig
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_DEFAULT_REGION: ap-southeast-1
volumes:
  helm-config:
  helm-cache:
