#!/bin/bash

build_dir_prefix=/tmp/tncharts
build_dir=${build_dir_prefix}$(openssl rand -hex 12);

rm -rf ${build_dir_prefix}* && mkdir -p ${build_dir}
for dir in ./stable/*/; do 
  helm package $dir --destination ${build_dir};
done

for dir in ./incubator/*/; do 
  helm package $dir --destination ${build_dir};
done

aws s3 cp s3://${CHARTMUSEUM_BUCKET}/index.yaml ${build_dir}/index.prev.yaml \
  --region ${AWS_REGION} \
  --profile ${AWS_PROFILE}

if [ ! -f "${build_dir}/index.prev.yaml" ]; then
  echo "ERROR in getting the current helm repo index before publishing the newest ones"
  exit 1;
fi


helm repo index --url http://${CHARTMUSEUM_BUCKET} --merge ${build_dir}/index.prev.yaml ${build_dir} 

aws s3 sync ${build_dir} s3://${CHARTMUSEUM_BUCKET} \
  --region ${AWS_REGION} \
  --profile ${AWS_PROFILE}
