---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "group-access-namespace.fullname" . }}
  labels:
    {{- include "group-access-namespace.labels" . | nindent 4 }}
subjects:
- kind: Group
  name: {{ .Values.group }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ include "group-access-namespace.fullname" . }}
  apiGroup: rbac.authorization.k8s.io