---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "group-access-namespace.fullname" . }}
  labels:
    {{- include "group-access-namespace.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  {{- range .Values.resources }}
    - {{ . | quote }}
  {{- end }}
  verbs:
  {{- range .Values.verbs }}
    - {{ . | quote }}
  {{- end }}