apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radius-auth-proxy.fullname" . }}-envvars
  labels:
    {{- include "radius-auth-proxy.labels" . | nindent 4 }}
data:
  {{- if .Values.session.passphrase }}
  SESSION_CRYPTO_PASSPHRASE: {{ .Values.session.passphrase | b64enc | quote }}
  {{- end }}