# Default values for radius-auth-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: abdennour/radius-auth-proxy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

uiAuthtype: form # UI_AUTH_TYPE (default: basic) (opts: basic, form)
radiusServer:
  hostname:  # RADIUS_SERVER_HOSTNAME - REQUIRED!!!
  port:   # RADIUS_SERVER_PORT
  secret: # RADIUS_SERVER_SECRET - REQUIRED!!!
radiusClient:
  proxiedUrl: # PROXY_URL (example: http://myapp:8080/) - REQUIRED!!!
  authTimeout: # # RADIUS_AUTH_TIMEOUT in seconds
  authRetries: # RADIUS_AUTH_RETRIES
  cookieValid: # RADIUS_COOKIE_VALID in minutes

session:
  passphrase: # SESSION_CRYPTO_PASSPHRASE 
  maxAge: ### SESSION_MAX_AGE -  in seconds
  cookieName: # SESSION_COOKIE_NAME (default: session)
  cookieAttrs: # SESSION_COOKIE_ATTRS # https://httpd.apache.org/docs/2.4/mod/mod_session_cookie.html
assets:
  # Check doc: https://github.com/abdennour/radius-auth-proxy#documentation
  # login.html: |
  #   <html> ...</html>
  #   <!-- Must include the form https://httpd.apache.org/docs/trunk/mod/mod_auth_form.html -->
  loginHtml:
  # Override the whole httpd.conf. 
  # We recommend to use env vars to build this file
  httpdConf:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8998

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
