{{ $root := . }}
{{- range $i,$app := .Values.subApps }}
---
apiVersion: {{ $root.Values.argocd.apiVersion | default $root.Chart.AppVersion }}
kind: Application
metadata:
  name: {{ include "argocd-app-of-apps.fullname" $root }}-{{ index $root.Values.variants $i }}
  labels:
    {{ $root.Values.variantName }}: {{ index $root.Values.variants $i }}
    {{- include "argocd-app-of-apps.labels" $root | nindent 4 }}
  {{- with $app.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
{{- with $app.spec }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
