# Default values for desktop-vnc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: abdennour/ubuntu-desktop #centos-xfce-vnc
  tag: 1.4.0-devtools-d0f1
  pullPolicy: IfNotPresent # Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

desktop:
  uid: 1000
  persistence:
    enabled: true
    # size: 8Gi
    # # storageClass: ReadWriteOnce
    # accessMode: ReadWriteOnce
    # mountPath: /headless/Downloads
    # annotations: {}
  persistenceShared:
    enabled: false
    # mountPath: /mnt/shared
    # claimName: internal-desktops-shared
  vnc_options:
    color_depth: "24" # VNC_COL_DEPTH
    resolution: "1280x1024" # VNC_RESOLUTION
    # password # VNC_PW default to "vncpassword"
    # view-only: false # VNC_VIEW_ONLY
  extraTools:
    docker: 19.03
    kubectl: 1.17.2
    helm: 3.0.2
    aws: 1.17.9
    git: 2.24.1
    kind: v0.7.0
  environment: []

podDisruptionBudget:
  minAvailable: 1
nodeDockerEngine:
  enabled: false
  dockerGroupIdOnNode: 994 #  docker gui in Amazon ec2 eks node
podDockerEngine:
  enabled: true
  version: 19.03
  resources: {}
    # requests:
    #   cpu: 20m
    #   memory: 512Mi
serviceAccount:
  annotations: {}
  clusterAccess:
    enabled: true
    rules: []
    namespaces: []

service:
  type: ClusterIP
  ports:
    http: 6901
    vnc: 5901

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
internetAccess:
  enabled: false
networkPolicy:
  enaled: true
  allowedNamespacesLabels:
    category: devtools
  apiServerEndpoints: [] # k -n default get ep kubernetes
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 2000m
    memory: 8192Mi
  requests:
    cpu: 1000m
    memory: 4096Mi

nodeSelector: {}

tolerations: []

affinity: {}
