{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "desktop-vnc.fullname" . }}-deny-all
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "desktop-vnc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress

# k -n default get ep kubernetes
{{- if .Values.networkPolicy.apiServerEndpoints }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1 
metadata:
  name: {{ include "desktop-vnc.fullname" . }}-allow-apiserver
spec:
  policyTypes:
  - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "desktop-vnc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    {{- range .Values.networkPolicy.apiServerEndpoints }}
    - ipBlock:
        cidr: {{- . | indent 1 }}
    {{- end }}

{{- end }}

{{- if .Values.networkPolicy.allowedNamespacesLabels }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "desktop-vnc.fullname" . }}-whitelist
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "desktop-vnc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
  - from:
    - namespaceSelector:
      {{- with .Values.networkPolicy.allowedNamespacesLabels }}
        matchLabels:
          {{- toYaml . | nindent 10 }}
      {{- end }}
  # egress:
  # - to:
  #   - namespaceSelector:
  #     {{- with .Values.networkPolicy.allowedNamespacesLabels }}
  #       matchLabels:
  #         {{- toYaml . | nindent 10 }}
  #     {{- end }}
  # - to:
  #   - namespaceSelector:
  #       matchLabels:
  #         name: kube-system
  #     podSelector:
  #       matchLabels:
  #         k8s-app: kube-dns
  #   ports:
  #    - port: 53
  #      protocol: UDP
  #    - port: 53
  #      protocol: TCP
{{- end }}

{{- if not .Values.internetAccess.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "desktop-vnc.fullname" . }}-egress-to-dns
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "desktop-vnc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
      ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP        
  - to:
    - namespaceSelector:
      {{- with .Values.networkPolicy.allowedNamespacesLabels }}
        matchLabels:
          {{- toYaml . | nindent 10 }}
      {{- end }}

{{- end }}

{{- end }}