{{- if .Values.desktop.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "desktop-vnc.fullname" . }}
  labels:
{{ include "desktop-vnc.labels" . | indent 4 }}
{{- with .Values.desktop.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  accessModes:
  - {{ .Values.desktop.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.desktop.persistence.size | quote }}
{{- if .Values.desktop.persistence.storageClass }}
{{- if (eq "-" .Values.desktop.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.desktop.persistence.storageClass }}"
{{- end }}
{{- end }}

{{- end }}