apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "desktop-vnc.fullname" . }}
  labels:
{{ include "desktop-vnc.labels" . | indent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "desktop-vnc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}