{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "desktop-vnc.fullname" . }}
  labels:
{{ include "desktop-vnc.labels" . | indent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}

{{- if .Values.serviceAccount.clusterAccess.enabled }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-{{ include "desktop-vnc.fullname" . }}
rules:
{{- with .Values.serviceAccount.clusterAccess.rules }}
{{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ include "desktop-vnc.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ include "desktop-vnc.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "desktop-vnc.fullname" . }}
    namespace: {{ .Release.Namespace }}
  {{ $root := . }}
  {{- range .Values.serviceAccount.clusterAccess.namespaces }}
  - kind: ServiceAccount
    name: {{ include "desktop-vnc.fullname" $root }}
    namespace: {{ . }}
  {{- end }}
{{- end }}

{{- end }}
