apiVersion: v1
kind: Service
metadata:
  name: {{ include "desktop-vnc.fullname" . }}
  labels:
{{ include "desktop-vnc.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.vnc }}
      targetPort: vnc
      protocol: TCP
      name: vnc
  selector:
    app.kubernetes.io/name: {{ include "desktop-vnc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
