apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radius-auth-proxy.fullname" . }}
  labels:
    {{- include "radius-auth-proxy.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "radius-auth-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config-assets: {{ include (print $.Template.BasePath "/configmap-assets.yaml") . | sha256sum }}
        checksum/config-envvars: {{ include (print $.Template.BasePath "/configmap-envvars.yaml") . | sha256sum }}
        checksum/secret-envvars: {{ include (print $.Template.BasePath "/secret-envvars.yaml") . | sha256sum }}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "radius-auth-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "radius-auth-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8998
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "radius-auth-proxy.fullname" . }}-envvars
            - secretRef:
                name: {{ include "radius-auth-proxy.fullname" . }}-envvars
          volumeMounts:
            - name:  assets
              mountPath: /opt/assets
          ### if eq .Values.uiAuthtype "form"
          # livenessProbe:
          #   httpGet:
          #     path: /login.html
          #     port: http
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /login.html
          #     port: http
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          ### else 
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          ### end 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: assets
        configMap:
          name: {{ include "radius-auth-proxy.fullname" . }}-assets
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
